// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dojsxuzcqtaxprcbmtgk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvanN4dXpjcXRheHByY2JtdGdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MjQyMzQsImV4cCI6MjA2NjMwMDIzNH0.DyzPojCPP1Ep99YbVfM4Axfv98nG7K1pLvz82qPRs7Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);